### PR TITLE
Fix broken l10n

### LINKED ISSUE #17: Translation in UI not shown
**Describe the bug**
I am using my computer with german interface. After installing this extension the UI is still in english. The translation file de.po is availible in the extension folder.

**To Reproduce**
1. You need a system language which is not english, f.e. german
2. Install this ext.
3. After relogin or Alt+F2 + r the UI of this ext. is still english

**Expected behavior**
See this ext. with german interface
**Screenshots**
---

**Desktop (please complete the following information):**
 - Ubuntu 19.04
 - Gnome 3.32.1

### PR DESCRIPTION
**Pull request by jose1711**
Fixes #17

### CODE REVIEW

**Review by HarlemSquirrel — COMMENTED** [review]
I realize now that we should be using `gnome-extensions pack` to create the extension zip file for distribution so I've updated the process here. We should only need the updates for  prefs.js here now.

Could you please try this out and update the PR? Thank you!

**Comment by jose1711** [comment]
When the changes you made will be visible on gnome extensions page?

**Comment by HarlemSquirrel** [comment]
@jose1711 I won't release a new version until we've verified this is working. You can manually install by cloning this repository and then following https://github.com/HarlemSquirrel/gnome-shell-extension-sensory-perception#build-and-install-on-gnome-40

**Comment by jose1711** [comment]
```
bin/build-dist.sh && gnome-extensions install --force dist/sensory-perception@HarlemSquirrel.github.io.shell-extension.zip
Linting...

> sensory-perception@1.0.0 test
> eslint .


Oops! Something went wrong! :(

ESLint: 8.3.0

ESLint couldn't find the config "eslint-config-gjs" to extend from. Please check that the name of the config is correct.

The config "eslint-config-gjs" was referenced from the config file in "/home/jose/tmp/gnome-shell-extension-sensory-perception/.eslintrc.yml".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
```

**Comment by HarlemSquirrel** [comment]
npm install

**Comment by jose1711** [comment]
> npm install

Thank you, that helped. Looks like just a couple changes are needed now - PR updated.

**Review by HarlemSquirrel — APPROVED** [review]

**Pull request merged**
